apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploynginxapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: deploynginxapp
  template:
    metadata:
      labels:
        app: deploynginxapp
        duowngtora: duowngtora-deploy-nginx
    spec:
      containers:
      - name: nginxapp
        image: ichte/swarmtest:node
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
