apiVersion: v1
kind: Pod
metadata:
  name: swarmtest-node
  labels:
    name: ungdung1
    ungdung: ungdung1
    duowngtora: duowngtora
spec:
  containers:
    - name: swarmtest-node
      image: ichte/swarmtest:node
      resources:
        limits:
          memory: "150M"
          cpu: "100m"
      ports:
        - containerPort: 80
