apiVersion: v1
kind: Pod
metadata:
  name: nginx-kube-test
  labels:
    name: nginx
    ungdung: ungdungnginx
spec:
  volumes:
    - name: vol-nginx
      volumePath: 
  containers:
    - name: nginx-kube-test
      image: nginx
      resources:
        limits:
          memory: "150M"
          cpu: "100m"
      ports:
        - containerPort: 80
