apiVersion: v1
kind: Pod
metadata:
  name: coretool
  labels:
   app: coretool
   duowngtora: duowngtora
   ungdung: ungdung-coretool
spec:
  containers:
    - name: core-tool
      image: ichte/coretools
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
      command: ["/bin/bash"]
      args: ["-c", "while true; do echo 'coretools is running'; sleep 10; done"]