apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: app1
    duowngtora: duowngtora-nginx-pod
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
    ports:
      - containerPort: 80

---
apiVersion: v1
kind: Pod
metadata:
  name: httpd-pod
  labels:
    app: app1
    duowngtora: duowngtora-httpd-pod
spec:
  containers:
  - name: httpd
    image: httpd
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
    ports:
      - containerPort: 80