apiVersion: v1
kind: Pod
metadata:
  name: pod-nginx
  labels:
    app: nginx
    duowngtora: duowngtora-pod-nginx
spec:
  nodeSelector:
    kubernetes.io/hostname: k3d-multiplenode-agent-1
  volumes:
    - name: nginx-vol
      hostPath:
       path: /home/nginx-vol
  containers:
    - name: nginx1
      image: nginx
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
      ports:
        - containerPort: 80
      volumeMounts:
        - name: nginx-vol
          mountPath: /usr/share/nginx/html