apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-test1
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: test1-storage-class
  hostPath:
    path: "/PersistentVolume/PvTest1"