apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-test1
spec:
  storageClassName: test1-storage-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 150Mi
  volumeMode: Filesystem
