apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-pv
spec:
  capacity:
    storage: 3Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: mariadb
  hostPath:
    path: "Kubernetes/Volumes/Mariadb"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pvc
spec:
  resources:
    requests:
      storage: 3Gi
  volumeMode: Filesystem
  storageClassName: mariadb
  accessModes:
    - ReadWriteOnce

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb-app
      type: dev
      duowngtora: duowngtora-mariadb-app
  template:
    metadata:
      labels:
        app: mariadb-app
        type: dev
        duowngtora: duowngtora-mariadb-app
    spec:
      volumes:
        - name: mariadb-vol
          persistentVolumeClaim:
            claimName: mariadb-pvc
      nodeSelector:
        kubernetes.io/hostname: k3d-wordpress-cluster-agent-1
      containers:
        - name: mariadb
          image: mariadb:latest
          resources:
            limits:
              memory: "512Mi"
              cpu: "600m"
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "123121123a"
            - name: MYSQL_DATABASE
              value: "duowngtora"
            - name: MYSQL_USER
              value: "duowngtora"
            - name: MYSQL_PASSWORD
              value: "123121123a"
          ports:
            - containerPort: 3306
          # volumeMounts:
          #   - name: mariadb-vol
          #     mountPath: "/var/lib/mysql"
      initContainers:
        - name: init-mariadb
          image: mariadb:latest
          command:
            - sh
            - "-c"
            - echo date

---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-svc
spec:
  type: NodePort
  selector:
    app: mariadb-app
    type: dev
    duowngtora: duowngtora-mariadb-app
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 31036
