apiVersion: v1
kind: Pod
metadata:
  name: rsapp
  labels:
    name: rsapp
    app: rsapp
    duowngtora: duowngtora
spec:
  containers:
    - name: app
      image: ichte/swarmtest:node
      resources:
        limits:
          cpu: "100m"
          memory: "128Mi"
      ports:
        - containerPort: 8085
