apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-tls-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-tls-pod
  template:
    metadata:
      labels:
        app: nginx-tls-pod
    spec:
      volumes:
        - name: nginx-cert-volume
          secret:
            secretName: secret-nginx-cert
      containers:
      - name: nginx
        image: duowngtora/kubernetes:nginx 
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
        - containerPort: 443
        volumeMounts:
        - name: nginx-cert-volume
          mountPath: /certs

---

apiVersion: v1
kind: Service
metadata:
  name: svc-nginx-tls
spec:
  type: NodePort
  selector:
    app: nginx-tls-pod
  ports:
  - port: 8080
    targetPort: 80
    nodePort: 30080
    name: port80
  - port: 443
    targetPort: 443
    nodePort: 30443
    name: port443 