apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-test1
spec:
  capacity:
    storage: 6Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: pv-nfs-test1-class
  nfs:
    path: "/mnt/DuowngTora/nfs_share"
    server: "192.168.1.33"
