apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-nfs-test-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: httpd-nfs-test-pod
  template:
    metadata:
      labels:
        app: httpd-nfs-test-pod
    spec:
      volumes:
        - name: nfs-test-vol
          persistentVolumeClaim:
            claimName: pvc-nfs-test1
        - name: nginx-cert-vol
          secret:
            secretName: secret-nginx-cert
      containers:
      - name: httpd
        image: duowngtora/kubernetes:httpd
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
        volumeMounts:
          - name: nfs-test-vol
            mountPath: /usr/local/apache2/htdocs
          - name: nginx-cert-vol
            mountPath: /certs


---

apiVersion: v1
kind: Service
metadata:
  name: httpd-nfs-test-service
spec:
  type: NodePort
  selector:
    app: httpd-nfs-test-pod
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31080