apiVersion: v1
kind: Pod
metadata:
  name: coretools
  labels:
    name: coretools
spec:
  containers:
  - name: coretools
    image: ichte/coretools
    resources:
      limits:
        memory: "128Mi"
        cpu: "300m"
    command:
      - /bin/sh
      - -c
      - sleep 600
