apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: daemonset-nginx
  labels:
    app: daemonset-nginx
    duowngtora: duowngtora-daemonset-nginx
spec:
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      volumes:
        - name: nginx-secret-vol
          secret:
            secretName: secret-nginx-cert
      containers:
        - name: nginx
          image: duowngtora/kubernetes:nginx
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
          ports:
          - containerPort: 80
          volumeMounts:
          - name: nginx-secret-vol
            mountPath: /certs