apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpanginx
  labels:
    app: hpa-nginx
    duowngtora: duowngtora-hpa-nginx
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: ReplicaSet
    name: rsnginx
  minReplicas: 6
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
