apiVersion: v1
kind: Pod
metadata:
  name: podnginx
  labels:
    app: appnginx
    duongtora: duowngtora-pod-nginx
spec:
  volumes:
    - name: nginx-vol
      hostPath:
        path: /home/nginxVol
  containers:
    - name: pod-nginx
      image: nginx
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: nginx-vol
