apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rsnginx
  labels:
    app: rsnginx
    duowngtora: duowngtora-rs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: appnginx
  template:
    metadata:
      name: app-nginx
      labels:
        app: appnginx
        duowngtora: duowngtora-rs-nginx
    spec:
      volumes:
        - name: nginx-vol
          hostPath:
            path: "/home/nginx-vol/"
      containers:
      - name: app-nginx
        image: nginx
        resources:
          limits:
           cpu: 100m
           memory: 128Mi
        ports:
          - containerPort: 80
        volumeMounts:
          - mountPath: "/usr/share/nginx/html/"
            name: nginx-vol

